### ISSUE TITLE
www.baloons.io failing to login with twitter

### ISSUE THREAD

**Issue by laisee** [rickyrauch/Balloons.IO#104]
Error: failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (/app/node_modules/passport-twitter/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:124:54)
    at Strategy.authenticate (/app/node_modules/passport-twitter/lib/passport-twitter/strategy.js:82:40)
    at attempt (/app/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
    at Passport.authenticate (/app/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
    at callbacks (/app/node_modules/express/lib/router/index.js:161:37)
    at param (/app/node_modules/express/lib/router/index.js:135:11)
    at pass (/app/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/app/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/app/node_modules/express/lib/router/index.js:33:10)
    at Context.next (/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)

**Comment by harshuopi** [comment]
What happened here? Live again? What do you mean?
