### ISSUE TITLE
Can't add the callback to facebook app settings

### ISSUE THREAD

**Issue by Tyvain** [rickyrauch/Balloons.IO#114]
When I try to add the callback's URL in facebook i get this message (also tried with localhost instead of 127.0.0):

```
is invalid because it is a Facebook url
```

**Comment by Tyvain** [comment]
I replace with localhost in 3 place: 
- on facebook:  'app domain'
- on facebook: site url ('http://localhost:6789/auth/facebook/callback')
- in config.js: "callback" : "http://localhost:6789/auth/facebook/callback"

Now i am getting this error:

```
failed to obtain access token (Error: connect EHOSTUNREACH)
    at /home/dev.recif.nc/sylvain.auger-leger/Balloons.IO/node_modules/passport-facebook/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:125:38
    at /home/dev.recif.nc/sylvain.auger-leger/Balloons.IO/node_modules/passport-facebook/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:176:18
    at ClientRequest.<anonymous> (/home/dev.recif.nc/sylvain.auger-leger/Balloons.IO/node_modules/passport-facebook/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:147:5)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1548:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1456:17)
    at Socket.emit (events.js:117:20)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
```

**Comment by impronunciable** [comment]
@Tyvain Did you create a facebook app for this? And if you did, using that Callback URL?

**Comment by Tyvain** [comment]
Yes Mickey I did :).

But thing is, I am behind a proxy. Does it matter?

**Comment by impronunciable** [comment]
@Tyvain It seems the request was stopped by your firewall https://github.com/npm/npm/issues/6820
